name: Trigger auto deployment for container-app-27chi6txf2ig6

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/container-app-27chi6txf2ig6-AutoDeployTrigger-7ca20433-177e-4a47-a094-29aa81fa0c18.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerregistry27chi6txf2ig6.azurecr.io
          username: ${{ secrets.CONTAINERAPP27CHI6TXF2IG6_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPP27CHI6TXF2IG6_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containerregistry27chi6txf2ig6.azurecr.io/container-app-27chi6txf2ig6:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP27CHI6TXF2IG6_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP27CHI6TXF2IG6_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP27CHI6TXF2IG6_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n container-app-27chi6txf2ig6 -g bradygshowme02 --server containerregistry27chi6txf2ig6.azurecr.io --username  ${{ secrets.CONTAINERAPP27CHI6TXF2IG6_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPP27CHI6TXF2IG6_REGISTRY_PASSWORD }}
            az containerapp update -n container-app-27chi6txf2ig6 -g bradygshowme02 --image containerregistry27chi6txf2ig6.azurecr.io/container-app-27chi6txf2ig6:${{ github.sha }}
